### ISSUE TITLE
Kamon 2.0 support

### ISSUE THREAD

**Issue by lukoyanov** [kamon-io/kamon-http4s#25]
Hey!

Is there any ETA on when kamon 2.0 will be supported in this module?

**Comment by dpsoft** [comment]
@lukoyanov ASAP

**Comment by kubukoz** [comment]
@dpsoft as far as I can see, there are some issues with the umbrella:

```
[error] sbt.internal.util.Init$RuntimeUndefined: References to undefined settings at runtime.
[error] setting(ScopedKey(Scope(Select(ProjectRef(git://github.com/kamon-io/kamon-sbt-umbrella.git,kamon-sbt-umbrella)), Select(ConfigKey(compile)), Zero, Zero),bloopGenerate)) at LinePosition((bloop.integrations.sbt.BloopDefaults.configSettings) SbtBloop.scala,159) referenced from ScopedKey(Scope(Select(ProjectRef(git://github.com/kamon-io/kamon-sbt-umbrella.git,kamon-sbt-umbrella)), Select(ConfigKey(compile)), Zero, Zero),pluginData)
[error] 	at sbt.internal.util.Init.sbt$internal$util$Init$$handleUndefined(Settings.scala:684)
[error] 	at sbt.internal.util.Init$$anon$9.apply(Settings.scala:688)
[error] 	at sbt.internal.util.Init$$anon$9.apply(Settings.scala:688)
[error] 	at sbt.internal.util.$tilde$greater$$anon$5.apply(TypeFunctions.scala:39)
[error] 	at sbt.internal.util.$tilde$greater$$anon$5.apply(TypeFunctions.scala:39)
[error] 	at sbt.std.FullInstance$.$anonfun$flatten$2(TaskMacro.scala:70)
[error] 	at scala.Function1.$anonfun$compose$1(Function1.scala:44)
[error] 	at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:40)
[error] 	at sbt.std.Transform$$anon$4.work(System.scala:67)
[error] 	at sbt.Execute.$anonfun$submit$2(Execute.scala:269)
[error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:16)
[error] 	at sbt.Execute.work(Execute.scala:278)
[error] 	at sbt.Execute.$anonfun$submit$1(Execute.scala:269)
[error] 	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:178)
[error] 	at sbt.CompletionService$$anon$2.call(CompletionService.scala:37)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[error] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[error] 	at java.lang.Thread.run(Thread.java:748)
[error] (ProjectRef(uri("git://github.com/kamon-io/kamon-sbt-umbrella.git"), "kamon-sbt-umbrella") / Compile / bloopGenerate) sbt.internal.util.Init$RuntimeUndefined: References to undefined settings at runtime.
[error] setting(ScopedKey(Scope(Select(ProjectRef(git://github.com/kamon-io/kamon-sbt-umbrella.git,kamon-sbt-umbrella)), Select(ConfigKey(compile)), Zero, Zero),bloopGenerate)) at LinePosition((bloop.integrations.sbt.BloopDefaults.configSettings) SbtBloop.scala,159) referenced from ScopedKey(Scope(Select(ProjectRef(git://github.com/kamon-io/kamon-sbt-umbrella.git,kamon-sbt-umbrella)), Select(ConfigKey(compile)), Zero, Zero),pluginData)
[error] Total time: 3 s, completed Aug 15, 2019 1:48:42 AM
Project loading failed: (r)etry, (q)uit, (l)ast, or (i)gnore?
```

**Comment by dpsoft** [comment]
hey @kubukoz I think that changing the umbrella line in plugins.sbt : https://github.com/kamon-io/kamon-jdbc/blob/master/project/plugins.sbt#L1 is enought to avoid this errror.

**Comment by kubukoz** [comment]
Joke's on you, I'm not able to run `sbt update` in that project either :P

If you have a solution, I'll try to do the updates (with the help of @scala-steweard) when my timezone wakes up. Thanks :)

**Comment by lukoyanov** [comment]
How is it going guys? @dpsoft @kubukoz

**Comment by garraspin** [comment]
I just created a PR https://github.com/kamon-io/kamon-http4s/pull/26

**Comment by dpsoft** [comment]
done by #27

**Comment by lukoyanov** [comment]
Thanks guys @dpsoft @garraspin @mladens

**Comment by garraspin** [comment]
Did tracing stopped working with this version (I'm missing trace ids) or do I need to change some configuration? I have configured server, client and execution context (with KamonSupport and ExecutorInstrumentation) but still no trace ids
